// Auto-generated TypeScript definitions for Canopus schemas
// Do not edit this file manually

export type Message = 
  | { type: 'Status' }
  | { type: 'Start' }
  | { type: 'Stop' }
  | { type: 'Restart' }
  | { type: 'Custom'; command: string };

export type Response = 
  | { type: 'Ok'; message: string }
  | { type: 'Error'; message: string; code?: string }
  | { type: 'Status'; running: boolean; uptimeSeconds: number; version?: string };

export interface DaemonConfig {
  host: string;
  port: number;
  logLevel: string;
  maxConnections: number;
}

export interface ClientConfig {
  daemonHost: string;
  daemonPort: number;
  timeoutSeconds: number;
}

export type Event = 
  | { type: 'DaemonStarted'; timestamp: string; version: string }
  | { type: 'DaemonStopped'; timestamp: string }
  | { type: 'ClientConnected'; timestamp: string; clientId: string }
  | { type: 'ClientDisconnected'; timestamp: string; clientId: string }
  | { type: 'Custom'; eventType: string; timestamp: string; data: any };

export interface SystemState {
  daemonRunning: boolean;
  activeConnections: number;
  uptimeSeconds: number;
  version: string;
  lastUpdated: string;
}
