# Clippy configuration for Canopus project
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 256
pass-by-value-size-limit = 512
enum-variant-size-threshold = 200
avoid-breaking-exported-api = true
suppress-restriction-lint-in-const = false
