[package]
name = "core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
tokio.workspace = true

[lib]
name = "core"
path = "src/lib.rs"
